name: Build & Deploy ElasticGPT Services

on:
  push:
    branches:
      - main
      - DEV
    paths:
      - 'elasticgpt-ui/**'
      - 'elasticgpt-api/**'
      - 'elasticgpt-backend/**'
  pull_request:
    branches: [main]
    types: [ready_for_review, synchronize, opened]
    paths:
      - 'elasticgpt-ui/**'
      - 'elasticgpt-api/**'
      - 'elasticgpt-backend/**'

jobs:
  build-and-deploy:
    name: Build Images & Deploy to GKE
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Generate Commit Hash
        id: vars
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV


      # - name: Authenticate with Google Cloud
      #   uses: google-github-actions/auth@v2
      #   with:
      #     project_id: elastic-edm
      #     workload_identity_provider: "projects/117436331624/locations/global/workloadIdentityPools/elasticgpt-ci-oidc/providers/elasticgpt-ci-oidc"
      #     service_account: "artifacts-egpt-writer@elastic-edm.iam.gserviceaccount.com"


      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker us-west1-docker.pkg.dev


      - name: Docker Login (Elastic Docker Registry)
        run: echo "${{ secrets.ELASTICGPT_GH_ACTIONS_DOCKER_PASSWORD }}" | docker login -u "${{ secrets.ELASTICGPT_GH_ACTIONS_DOCKER_USERNAME }}" --password-stdin docker.elastic.co


      - name: Build & Push UI Image
        run: |
          IMAGE="us-west1-docker.pkg.dev/elastic-edm/idea-artifact-registry-elasticgpt/elasticgpt-ui"
          docker build -t $IMAGE:${{ env.commit_hash }} ./elasticgpt-ui --platform linux/amd64
          docker push $IMAGE:${{ env.commit_hash }}


      - name: Build & Push API Image
        run: |
          IMAGE="us-west1-docker.pkg.dev/elastic-edm/idea-artifact-registry-elasticgpt/elasticgpt-api"
          docker build -t $IMAGE:${{ env.commit_hash }} ./elasticgpt-api --platform linux/amd64
          docker push $IMAGE:${{ env.commit_hash }}


      - name: Build & Push Backend Image
        run: |
          IMAGE="us-west1-docker.pkg.dev/elastic-edm/idea-artifact-registry-elasticgpt/elasticgpt-backend"
          docker build -t $IMAGE:${{ env.commit_hash }} ./elasticgpt-backend --platform linux/amd64
          docker push $IMAGE:${{ env.commit_hash }}


      - name: Install GKE Auth Plugin
        run: gcloud components install gke-gcloud-auth-plugin


      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials elastic-idea-apps-platform-dev-primary \
            --project elastic-edm-dev \
            --region us-west1


      - name: Deploy via Kustomize with tag substitution
        run: |
          export TAG=${{ env.commit_hash }}
          cd deployments/web_app/overlay/dev
          envsubst < <(kustomize build .) | kubectl apply -f -


      - name: Verify Rollouts
        run: |
          NAMESPACE=elasticgpt
          kubectl rollout status deployment/ui -n $NAMESPACE
          kubectl rollout status deployment/api -n $NAMESPACE
          kubectl rollout status deployment/backend -n $NAMESPACE